client/src/App.css

I added branded fonts and colors to the App.css to be used throughout the app.
I also added body colors and link styling which serve as an example of how to use the root variables throughout the app.

Root Styling

---

server/models/User.js

fixed typo in User model

---

client/src/pages/Dashboard.jsx
client/src/pages/Signup.jsx

We added templates from Material UI for the Dashboard and Signup section. Next step is styling.

updated dashboard and signup

---

server/config/emailConfig.js

Updated the HTML for the welcome email to send a stylized message with links to the app using beefree.io
May want to move template to its own file at a later date because its an eyesore.

updated welcome email template

---

README.md

Added README formatting
Filled in Description, Credits, and License info
_Usage section will need to be completed after app is done_

updated README with description, credits, and license

---

client/.gitignore
client/public/index.html
client/src/pages/Search.jsx

Added .env file to src (directions for adding your own in Trello)

Api updates

---

client/src/client.js
client/src/components/Copyright.jsx
client/src/pages/Signup.jsx
client/src/utils/auth.js
client/src/utils/mutations.js

- Form reflects user model
- Users can be created
- Added loader
- Fixed disable sign up button
Still needs:

Signup fix

---

client/src/components/SearchResultDetail.jsx
client/src/utils/authHook.js
client/src/utils/mutations.js

Users can click the add plant button next to search results and that plant will be added to their plant array.
Data is ready for the garden and single plant views.

users can add plants from the search

---

client/src/pages/Search.jsx
client/src/pages/Signup.jsx
client/src/utils/mutations.js

notification seems to no longer exist so removed from client side mutation

removed notification on mutation for plant

---

client/src/components/SearchResultDetail.jsx
server/schema/resolvers.js

Updated resolvers to allow users to log in.

fixed resover so users can log in

---

client/src/pages/Signup.jsx

Added blurs for errors in sign up form.

added blurs for signup form

---

client/src/pages/MyGarden.jsx
client/src/pages/PlantDetails.jsx
client/src/utils/mutations.js
server/server.js

Added delete button and functionality to Plant Details page.
Query will get new data on redirect instead of pulling from cache.

Added delete button

---

server/utils/auth.js

added secret to env
add to your own env:
JWT_SECRET="mysecretsshhhhh"

secret in env

---

client/src/pages/AccountInfo.jsx
client/src/pages/Signup.jsx

refactored the Login form to update user email and username

update username and email

---

client/src/App.js
client/src/components/Header.jsx

Account info for user to edit their username and password

accountInfo.jsx

---

client/src/pages/MyGarden.jsx
client/src/pages/PlantDetails.jsx

Images on the MyGarden view and Plant Details page are now rounded. Plant details page also has the notes sections with an add note and delete note button added.

rounded imgs and added notes section with buttons

---

client/src/pages/MyGarden.jsx
client/src/pages/PlantDetails.jsx
client/src/pages/plantDetails.css

- Rearranged notes
- Added media queries
Functionality still needed.
- Add note button currently DELETES plant
- Notes array not set up to populate
- Icons to right of notes nonfunctional

Plant details page updates

---

client/src/App.js
client/src/components/Header.jsx
client/src/pages/AccountInfo.jsx
client/src/pages/Login.jsx
client/src/utils/authHook.js
client/src/utils/mutations.js

AccountInfo component rendering now that the path has been created and user now able to update their username and email. Need to make the delete profile to connect to backend

accountInfo page rendering and adding a delete button for profile

---

server/schema/resolvers.js
server/schema/typeDefs.js

added deleteUser to typeDefs and Resolvers. Working in GQL

deleteUser added

---

client/src/pages/PlantDetails.jsx
client/src/utils/mutations.js

- Notes can be added from text field using the add note button
- On completion, queries are refetched instead of pulling from cache to allow future functionality
- Notes still need to be populated on the page. That will be my next task.

Notes can be added to plant note array

---

client/src/pages/PlantDetails.jsx
client/src/utils/mutations.js

Notes array is populated on the page.
Notes are formatted according to figma mock up.
Edit/Delete notes need functionality.

REVIEW AFTER NOTES ARRAY Saved notes

---

client/src/pages/AccountInfo.jsx

Delete user succesfully executes and redirects user to the home page

delete user seems to be functioning properly

---

client/src/pages/PlantDetails.jsx
client/src/utils/mutations.js
server/schema/resolvers.js

delete note works
